---
# Source: vitess/templates/application.yaml
apiVersion: apperator.portworx.io/v1alpha1
kind: Application
metadata:
  name: mysql-test
  namespace: mysql
spec:
  objects:
  - apiVersion: planetscale.com/v2
    kind: VitessCluster
    metadata:
      name: mysql-test
    spec:
      images:
        vtctld: vitess/lite:v6.0.20-20200429
        vtgate: vitess/lite:v6.0.20-20200429
        vttablet: vitess/lite:v6.0.20-20200429
        vtbackup: vitess/lite:v6.0.20-20200429
        mysqld:
          mysql56Compatible: vitess/lite:v6.0.20-20200429
        mysqldExporter: prom/mysqld-exporter:v0.11.0
      cells:
      - name: zone1
        gateway:
          authentication:
            static:
              secret:
                name: example-cluster-config
                key: users.json
          replicas: 1
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 256Mi
      vitessDashboard:
        cells:
        - zone1
        extraFlags:
          security_policy: read-only
        replicas: 1
        resources:
          limits:
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
      keyspaces:
      - name: commerce
        turndownPolicy: Immediate
        partitionings:
        - equal:
            parts: 2
            shardTemplate:
              databaseInitScriptSecret:
                name: example-cluster-config
                key: init_db.sql
              replication:
                enforceSemiSync: false
              tabletPools:
              - cell: zone1
                type: replica
                replicas: 3
                vttablet:
                  extraFlags:
                    db_charset: utf8mb4
                  resources:
                    requests:
                      cpu: 100m
                      memory: 256Mi
                mysqld:
                  resources:
                    requests:
                      cpu: 100m
                      memory: 256Mi
      updateStrategy:
        type: Immediate
